main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('pokemon/', views.pokemon_index, name="index"),
  path('pokemon/<int:pokemon_id>/', views.pokemon_detail, name='detail'),
  path('pokemon/create/', views.PokemonCreate.as_view(), name="pokemon_create"),
  path('pokemon/<int:pk>/update/', views.PokemonUpdate.as_view(), name="pokemon_update"),
  path('pokemon/<int:pk>/delete/', views.PokemonDelete.as_view(), name="pokemon_delete"),
  path('pokemon/<int:pokemon_id>/feed_berry/', views.feed_berry, name="feed_berry")
]

pokemoncollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

BERRIES = (
  ('O', "Oran"),
  ('C', "Chesto"),
  ('P', 'Pecha'),
  ('R', 'Rawst'),
  ('A', 'Aspear'),
  ('S', 'Sitrus')
)

# Create your models here.
class Pokemon(models.Model):
  name = models.CharField(max_length=100)
  type = models.CharField(max_length=100)
  height = models.IntegerField()
  weight = models.IntegerField()
  description = models.TextField(max_length=250)
  level = models.IntegerField()

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('detail', kwargs={'pokemon_id': self.id})

class Feeding(models.Model):
  date = models.DateField('feeding date')
  berry = models.CharField(
    max_length=1, 
    choices=BERRIES, 
    default=BERRIES[0][0]
    )

  pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)

  def __str__(self):
    return f'{self.get_berry_display()} on {self.date}'
  
  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'berry']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Pokemon
from .forms import FeedingForm

# Create your views here.
from django.http import HttpResponse

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def pokemon_index(request):
  pokemon = Pokemon.objects.all()
  return render(request, 'pokemon/index.html', {'pokemon': pokemon })

def pokemon_detail(request, pokemon_id):
  pokemon = Pokemon.objects.get(id=pokemon_id)
  feeding_form = FeedingForm()
  return render(request, 'pokemon/detail.html', { 'pokemon': pokemon, 'feeding_form': feeding_form })

def feed_berry(request, pokemon_id):
  form = FeedingForm(request.POST)
  if form.is_valid():
    new_feeding = form.save(commit=False)
    new_feeding.pokemon_id = pokemon_id
    new_feeding.save()
  return redirect('detail', pokemon_id=pokemon_id)

class PokemonCreate(CreateView):
  model = Pokemon
  fields = '__all__'

class PokemonUpdate(UpdateView):
  model = Pokemon
  fields = ['type', 'height', 'weight', 'description', 'level']

class PokemonDelete(DeleteView):
  model = Pokemon
  success_url = '/pokemon/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Pokemon Collector</h1>
<hr />
<p>Hire the Pokemon Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Pokemon Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;PokemonCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'pokemon_create' %}">Add A Pokemon</a></li>
          <li><a href="{% url 'index' %}">View All My Pokemon</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Pokemon Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<img src="https://i.imgur.com/FfcxWid.png" alt="Pokedex">
{% endblock %}

main_app/templates/main_app/pokemon_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Pokemon</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' pokemon.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/pokemon_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Pokemon</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/pokemon/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Pokemon Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ pokemon.name }}</span>
        <p>Type: {{ pokemon.type }}</p>
        <p>Height: {{ pokemon.height }} ft</p>
        <p>Weight: {{ pokemon.weight }} lbs</p>
        <p>Description: {{ pokemon.description }}</p>
        {% if pokemon.level > 0 %}
        <p>Level: {{ pokemon.level }}</p>
        {% else %}
        <p>Level: N/A</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'pokemon_update' pokemon.id %}">Edit</a>
        <a href="{% url 'pokemon_delete' pokemon.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'feed_berry' pokemon.id %}" method="post">
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Feed Berry">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Berry</th></tr>
      </thead>
      <tbody>
        {% for feeding in pokemon.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_berry_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  var selectEl = document.getElementById('id_berry');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/pokemon/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Pokemon List</h1>

{% for pokemon in pokemon %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ pokemon.name }}</span>
      <p>Type: {{ pokemon.type }}</p>
      <p>Height: {{ pokemon.height }}</p>
      <p>Weight: {{ pokemon.weight }}</p>
      <p>Description: {{ pokemon.description }}</p>
      {% if pokemon.level > 0 %}
        <p>Level: {{ pokemon.level }}</p>
      {% else %}
        <p>Level: N/A</p>
      {% endif %}
    </div>
  </div>
{% endfor %}

{% endblock %}